apiVersion: v1
kind: Service
metadata:
  labels:
    name: coordinator
  name: coordinator
spec:
  ports:
  - name: coo-http
    nodePort: $COORDINATOR_NODE_PORT_OUT
    port: $COORDINATOR_SERVICE_PORT_OUT
    protocol: TCP
    targetPort: $COORDINATOR_POD_PORT_OUT
  - name: coo-http2
    nodePort: $COORDINATOR_NODE_PORT_IN
    port: $COORDINATOR_SERVICE_PORT_IN
    protocol: TCP
    targetPort: $COORDINATOR_POD_PORT_IN
  selector:
    app: coordinator
  type: NodePort
