apiVersion: v1
kind: ConfigMap
metadata:
  name: k8s-conf
data:
  k8sconfig.yaml: |+
    apiVersion: v1
    clusters:
    - cluster:
        server: $K8S_SERVER_URL
        insecure-skip-tls-verify: true
      name: kubernetes
    contexts:
    - context:
        cluster: kubernetes
        user: basic-authentication
      name: basic-authentication@kubernetes
    - context:
        cluster: kubernetes
        user: cert-authentication
      name: cert-authentication@kubernetes
    current-context: cert-authentication@kubernetes
    kind: Config
    preferences: {}
    users:
    - name: basic-authentication
      user:
        username: $K8S_USERNAME
        password: $K8S_PASSWORD
    - name: cert-authentication
      user:
        client-certificate-data: $K8S_CLIENT_CERTIFICATE_DATA
        client-key-data: $K8S_CLIENT_KEY_DATA
