apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: $MYSQL_IMAGE
          ports:
            - containerPort: $MYSQL_POD_PORT
          resources:
            limits:
              cpu: "1"
              memory: "1Gi"
            requests:
              cpu: "250m"
              memory: "256Mi"
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: $MYSQL_PASSWORD_SECRET
                  key: password
          volumeMounts:
            - name: mysql-volume
              mountPath: /var/lib/mysql
      volumes:
        - hostPath:
            path: $MYSQL_VOLUME_PATH
            type: DirectoryOrCreate
          name: mysql-volume
