apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: nacos
  name: nacos
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      name: nacos
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: nacos
    spec:
      containers:
      - env:
        - name: MODE
          value: standalone
        - name: SPRING_DATASOURCE_PLATFORM
          value: mysql
        - name: PREFER_HOST_MODE
          value: hostname
        image: $NACOS_IMAGE
        imagePullPolicy: Always
        name: nacos
        resources:
          limits:
            cpu: "1"
            memory: 2Gi
          requests:
            cpu: "1"
            memory: 2Gi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /home/nacos/conf/application.properties
          name: nacos-cm
          subPath: application.properties
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          items:
          - key: application.properties
            path: application.properties
          name: nacos-cm
        name: nacos-cm
