apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: $REDIS_IMAGE
          ports:
            - containerPort: $REDIS_POD_PORT
          resources:
            limits:
              cpu: "1"
              memory: "1Gi"
            requests:
              cpu: "250m"
              memory: "256Mi"
          volumeMounts:
            - name: redis-volume
              mountPath: /data
            - name: redis-conf
              mountPath: /etc/redis.conf
              subPath: redis.conf
              readOnly: true
      volumes:
        - hostPath:
            path: $REDIS_VOLUME_PATH
            type: DirectoryOrCreate
          name: redis-volume
        - name: redis-conf
          configMap:
            name: $REDIS_CONF